

 const actionTypes={
    FETCH_GAME_DATA_REQUEST: "FETCH_GAME_DATA_REQUEST",
    FETCH_GAME_DATA_SUCCESS: "FETCH_GAME_DATA_SUCCESS",
    FETCH_GAME_DATA_FAILURE: "FETCH_GAME_DATA_FAILURE",
}

export default actionTypes